#!/usr/bin/env python3
"""Convert an ICsprout55 standard-cell CDL netlist into an ngspice-ready SPICE netlist.

Usage: cdl_to_spice.py <input.cdl> <output.spice>

Changes applied (the CDL itself is never modified):
  - Repeated, identical .SUBCKT definitions (helper cells such as NAND2, TG)
    are kept only once; ngspice rejects duplicate definitions.
  - MOS lines (M...) become subcircuit calls (XM...), because every MOS model
    in the PDK is a subcircuit wrapper (nm1p2_hvt_lp, ...).
  - The CDL "/" separator on X lines is removed.
  - Layout annotations ($X=.. $Y=.. $D=..) are stripped.
  - Parameters used inside a subcircuit but not declared (nw, pw, nl, pl, ...)
    get a default on the .SUBCKT line, as ngspice requires.
"""
import re
import sys

NUM_RE = re.compile(r"^[-+]?(\d+\.?\d*|\.\d+)([eE][-+]?\d+)?[a-zA-Z]*$")
DEFAULT_W = "200n"
DEFAULT_L = "60n"


def join_continuations(lines):
    """Joins '+' continuation lines onto the previous line."""
    out = []
    for line in lines:
        if line.startswith("+") and out:
            out[-1] += " " + line[1:].strip()
        else:
            out.append(line.rstrip("\n"))
    return out


def convert_device(line):
    toks = [t for t in line.split() if not t.startswith("$") and t != "/"]
    if toks[0][0] in "Mm":
        toks[0] = "X" + toks[0]
    return " ".join(toks)


def undeclared_params(header, body):
    """Returns {name: default} for identifiers used as parameter values in body."""
    declared = {t.split("=")[0].lower() for t in header.split()[2:] if "=" in t}
    params = {}
    for line in body:
        if line.startswith("*"):
            continue
        for key, val in re.findall(r"(\w+)\s*=\s*([^\s=]+)", line):
            if NUM_RE.match(val) or val.lower() in declared or val.lower() in params:
                continue
            if not re.match(r"^[A-Za-z_]\w*$", val):
                continue
            params[val.lower()] = DEFAULT_L if key.lower() == "l" else DEFAULT_W
    return params


def convert(text):
    lines = join_continuations(text.splitlines())
    out = []
    seen = {}
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.upper().startswith(".SUBCKT"):
            out.append(line)
            i += 1
            continue

        # Collect the whole subcircuit
        j = i
        while not lines[j].upper().startswith(".ENDS"):
            j += 1
        header, body, ends = line, lines[i + 1:j], lines[j]
        name = header.split()[1]
        i = j + 1

        key = "\n".join(re.sub(r"\s+", " ", l).strip() for l in [header] + body)
        if name in seen:
            if seen[name] != key:
                sys.exit(f"Subcircuit {name} defined twice with different bodies")
            # Drop the duplicate along with the comment banner just before it
            while out and (out[-1].startswith("*") or not out[-1].strip()):
                out.pop()
            continue
        seen[name] = key

        params = undeclared_params(header, body)
        if params:
            header += " " + " ".join(f"{k}={v}" for k, v in params.items())
        out.append(header)
        for b in body:
            out.append(b if b.startswith("*") or not b.strip() else convert_device(b))
        out.append(ends)
    return "\n".join(out) + "\n"


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, dst = sys.argv[1:]
    with open(src) as f:
        text = f.read()
    header = (f"* Generated by scripts/cdl_to_spice.py from {src.split('/')[-1]}\n"
              "* ngspice-compatible copy; edit the generator, not this file.\n")
    with open(dst, "w") as f:
        f.write(header + convert(text))


if __name__ == "__main__":
    main()
